### ISSUE TITLE
How do i change the method ? #9

### ISSUE THREAD

**Issue by razvanab** [Kosinkadink/ComfyUI-Advanced-ControlNet#128]
When using the xinsir/controlnet-union-sdxl-1.0 model in comfyui with ControlNet_Plus_Plus, how do I change the method?

**Comment by Kosinkadink** [comment]
ControlNetPlusPlus is not supported yet. I was made aware of the code being released only 20 minutes ago, so I'll work on supporting it today.

**Comment by razvanab** [comment]
I see. Thank you.

**Comment by Kosinkadink** [comment]
A couple days ago I pushed code to select ControlNet++ mode. Requires latest ComfyUI to use.

**Comment by Kosinkadink** [comment]
![image](https://github.com/user-attachments/assets/4e565c3c-6df6-4762-9251-405b22664277)

**Comment by razvanab** [comment]
Thank you.

**Comment by glyfspace** [comment]
hey! I had an interesting use case where I would using the traditional "Load ControlNet Model" with the ControlNet++ model and it provided some interesting results, however now I can't do that since it raises this exception.  

`raise Exception("ControlNet++ model detected; must be loaded using the Load ControlNet++ Model nodes.")`

I appreciate you integrating the "Load ControlNet++ Model (Single)" node, but could you remove that exception so we can use the traditional controlnet loader with the Controlnet++ models? Thanks!

**Comment by glyfspace** [comment]
Thanks!
