### ISSUE TITLE
[SparseCtrl] Where are the weights of the Depth SparseCtrl model?

### ISSUE THREAD

**Issue by brayevalerien** [Kosinkadink/ComfyUI-Advanced-ControlNet#146]
Thanks for including SparseCtrl in your extension, it is valuable for video generation. I've been using the RGB version for quite a long time but I want to try the Scribble and Depth models, but I'm only able to find the weights for the RGB and the Scribble versions [on the 🤗 repo](https://huggingface.co/guoyww/animatediff/tree/main).
Do you know where I can find the weights for the Depth version?

Also including some form of automatic download of the SparseCtrl models when running the nodes for the first time would be great.

**Comment by Kosinkadink** [comment]
Unfortunately, the depth Sparse model was never released.

As for automatic downloads, I've avoided implementing that due to seeing other custom nodes sometimes failing to download models completely, resulting in unloadable models that result in a lot of duplicate GitHub issue reports. At some point I'll probably implement it, but for the time being that is not something I want to worry about.

**Comment by brayevalerien** [comment]
Got it, thank you for answering.
