### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by za-wa-n-go** [Kosinkadink/ComfyUI-Advanced-ControlNet#2]
Where do you attach the Weight?

**Comment by Kosinkadink** [comment]
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/7365912/cefd2459-7acf-4e98-a413-288f085ab767)

or 

![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/7365912/de7a5234-7cd6-4c29-abac-11772e14af1b)

Each Weight node contains its own independent TimestepKeyframe as well, allowing you to only need 1 node instead of 2 in the cases where no changes in the weights should happen during generation (the two pictures above give equivalent results). The TimestepKeyframes don't actually do anything right now besides being middlemen for the weights and latent keyframes. I will add functionality (and actual documentation in the README to this over the weekend.

**Comment by Kosinkadink** [comment]
I should also note, when no weight is attached/no timestep_keyframe is attached, it defaults to default weights as usual.
