### ISSUE TITLE
How to connect the node  like A111 "my prompt is more important"

### ISSUE THREAD

**Issue by xueqing0622** [Kosinkadink/ComfyUI-Advanced-ControlNet#24]
I'm going to make a single image use controlnet like A111, is this the right way to connect the node like this?
![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/fed9d66c-5379-4bba-b346-5dbc3b2bb7c5)

![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/87726948-e38b-470d-b6e4-877c960a64ad)
![image](https://github.com/comfyanonymous/ComfyUI/assets/114840118/b2657331-490d-409c-81c7-b3a100a3e24f)

**Comment by Kosinkadink** [comment]
Yep, that would be one way to hook it up. To clarify, the Scaled Soft ControlNet Weights node and the Soft ControlNet Weights node, with the default values, are the same: 
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/7365912/7c679e32-70f3-4076-8f1b-611c8075f343)

The only difference is, Scaled Soft ControlNet Weights will automatically scale the values as you wish, while Soft ControlNet Weights lets you manually change any layer of the controlnet, which is more involved. So you can just use the Scaled Soft ControlNet Weights node instead - and changing the base_multiplier on it can let you give the controlnet more freedom (AKA, make prompt even more important) if decreasing the value, or give controlnet less freedom (AKA, make prompt 'less' important) if increasing the value closer to 1. The default value, 0.825, is the value used by "my prompt is more important" in Auto1111 as explained in that screenshot you have, so that's why it's that value by default.

If you are not using any other features of the Timestep Keyframe node, you can also skip it by connecting the TIMESTEP_KEYFRAME output of the ControlNet Weights nodes to Load ControlNet Model (Advanced). Internally, it creates a placeholder Timestep Keyframe with default values so that you don't have to have a middleman Timestep Keyframe to just use the weights if not using anything else on the Timestep Keyframe:
![image](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/7365912/323935c4-b477-43a2-aae9-32ed2d232a6d)

**Comment by xueqing0622** [comment]
Thx, Kosinkadink, This helps me a lot to understand this node. 
Have a nice day!

**Comment by curlysasha** [comment]
What value for "controlnet is more important"?

**Comment by alenknight** [comment]
> my prompt is more important

i too am curious about this.  i figured out how to get it "balanced" and "my prompt is more important"... but controlnet is more important seems to be confusing me.  i can KINDA get there by "flip weights" option....  and reducing it very low... but it's not 1:1... not even close.

**Comment by Kosinkadink** [comment]
"ControlNet is more important" is not implemented ter. I'll look into it at end of February/start of March

**Comment by rohitpaul23** [comment]
@Kosinkadink any improvement ?

**Comment by yano** [comment]
https://github.com/comfyanonymous/ComfyUI/discussions/605 This connection is similar to 'My prompt is more important' and may be helpful.

**Comment by Kosinkadink** [comment]
"ControlNet is more important" is now supported as of the latest Advanced-ControlNet update, explained here and on the README:
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/issues/87#issuecomment-2116370541
