### ISSUE TITLE
import error comfyui

### ISSUE THREAD

**Issue by freewely** [Kosinkadink/ComfyUI-Advanced-ControlNet#55]
![c2](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/114961562/f8c63cc2-b60d-41d4-b9a7-057ccb6e4cb2)
![c1](https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet/assets/114961562/007df660-f963-491a-ba2b-3f0723074da8)

I can't solve this problem for two days. It started suddenly.
I am using the following colab notebook.

https://github.com/dreammachineai/ComfyCloud/blob/main/ComfyCloud_v0_1_2.ipynb

**Comment by akabez** [comment]
Having the same issue on ComfyUI (everything is updated in comfy)

**Comment by Kosinkadink** [comment]
Scroll up in your console, it will give you a full error stack about why it failed to load. And send that full error stack my way.

**Comment by skingfx** [comment]
I am having the exact same issue with exactly the same collab...
here is the relevant console output...thank you in advance...

Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/__init__.py", line 1, in <module>
    from .adv_control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 12, in <module>
    from .control_sparsectrl import SparseControlNet, SparseCtrlMotionWrapper, SparseMethod, SparseSettings, SparseSpreadMethod, PreprocSparseRGBWrapper
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_sparsectrl.py", line 30, in <module>
    from .utils import TimestepKeyframeGroup, disable_weight_init_clean_groupnorm, prepare_mask_batch
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 228, in <module>
    class disable_weight_init_clean_groupnorm(comfy.ops.disable_weight_init):
AttributeError: module 'comfy.ops' has no attribute 'disable_weight_init'

Cannot import /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet module for custom nodes: module 'comfy.ops' has no attribute 'disable_weight_init'

**Comment by Kosinkadink** [comment]
@skingfx Your comfyui is terribly outdated. Update your ComfyUI, and your error will go away.

**Comment by skingfx** [comment]
Thank you for the prompt reply...\
I have updated this colab version of comfy several times yesterday, perhaps this one is out of date...I will try the original fork of comfy ComfyUI and report back...again thank you.

**Comment by skingfx** [comment]
my apologies for the delay...I keep getting the following  error when trying to load Advanced-ControlNet from the ComfyUI Manager...
Cmd('git') failed due to: exit code(128)
I have already tried both disabling and uninstalling AdvancedControlNet via the manager....restarting
doesnt work....
I also tried manually deleting the ComfyUI/custom_nodes/ComfyUI-Advanced-ControNet and restarting and then reinstalling...I keep getting this error (relevant output below)...(I realize this is different than original issue..and wondered if you have. suggestion...on how to fix...yesterday I successfully scripted the install of AdvancedControlNet via my colab notebook...should I go this route again?...thank you again.

Total VRAM 15102 MB, total RAM 12979 MB
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 1791 [248d9125] | Released on '2023-12-07'

[rgthree] Loaded 18 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json 

INFO:comfyui-prompt-control:Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
INFO:comfyui-prompt-control:Weight interpretations available: comfy,perp
INFO:comfyui-prompt-control:Normalization types available: none
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
Downloading: "https://download.pytorch.org/models/mobilenet_v2-b0353104.pth" to /root/.cache/torch/hub/checkpoints/mobilenet_v2-b0353104.pth
/content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:25: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
2024-01-18 21:23:44.902722: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-18 21:23:44.902792: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-18 21:23:44.904180: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-18 21:23:45.947592: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[comfy_mtb] | INFO -> loaded 60 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
FizzleDorf Custom Nodes: Loaded

Import times for custom nodes:
   1.2 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/sdxl-recommended-res-calc
   1.2 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-HQ-Image-Save
   1.2 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/cg-use-everywhere
   1.8 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui-optical-flow
   2.6 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   3.8 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfy-nodes
   6.7 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
   7.1 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyMath
   7.2 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_FizzNodes
   8.1 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui-prompt-control
   8.8 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/steerable-motion
  10.6 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
  11.0 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/efficiency-nodes-comfyui
  13.6 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
  19.3 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
  20.9 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/rgthree-comfy
  22.0 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Manager
  23.6 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
  39.8 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux
  77.0 seconds: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfy_mtb


ComfyUI finished loading, trying to launch cloudflared (if it gets stuck here cloudflared is having issues)

This is the URL to access ComfyUI: https://folk-lonely-agent-clicks.trycloudflare.com/                                        |
FETCH DATA from: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Install custom node 'ComfyUI-Advanced-ControlNet'
install: ['https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet']
Download: git clone 'https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet'
  0% 0.0/251.0 [00:01<?, ?it/s]           Install(git-clone) error: https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet / Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v --recursive --progress -- https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
  0% 0.0/251.0 [00:01<?, ?it/s]
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

**Comment by Kosinkadink** [comment]
Something seems to be up with your setup, try deleting the entirety of Advanced-ControlNet. If the .git directory inside there is screwed up for some reason on your local machine, that could be the cause. Other than that, try googling the git error. One thing I can guarantee is it's not an issue with Advanced-ControlNet itself. Once you find a solution, be sure to post it here in case someone runs into the same problem with collab!

**Comment by skingfx** [comment]
ok...manually deleted Advanced-ControlNet directory...
and rebooted my google colab ComfyUi session...
I get this error which is similar to freewely original error...

AttributeError: module 'comfy.ops' has no attribute 'disable_weight_init'

full output below:

Total VRAM 15102 MB, total RAM 12979 MB
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
### Loading: ComfyUI-Manager (V1.5.2)
### ComfyUI Revision: 1791 [248d9125] | Released on '2023-12-07'

[rgthree] Loaded 18 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json 

INFO:comfyui-prompt-control:Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
INFO:comfyui-prompt-control:Weight interpretations available: comfy,perp
INFO:comfyui-prompt-control:Normalization types available: none
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /content/drive/MyDrive/AI/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
2024-01-18 23:11:09.927402: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-18 23:11:09.927461: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-18 23:11:09.928810: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-18 23:11:11.099399: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[comfy_mtb] | INFO -> loaded 60 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
FizzleDorf Custom Nodes: Loaded
Traceback (most recent call last):
  File "/content/drive/MyDrive/AI/ComfyUI/nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/__init__.py", line 1, in <module>
    from .adv_control.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/nodes.py", line 6, in <module>
    from .control import load_controlnet, convert_to_advanced, is_advanced_controlnet
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 12, in <module>
    from .control_sparsectrl import SparseControlNet, SparseCtrlMotionWrapper, SparseMethod, SparseSettings, SparseSpreadMethod, PreprocSparseRGBWrapper
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control_sparsectrl.py", line 30, in <module>
    from .utils import TimestepKeyframeGroup, disable_weight_init_clean_groupnorm, prepare_mask_batch
  File "/content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 228, in <module>
    class disable_weight_init_clean_groupnorm(comfy.ops.disable_weight_init):
AttributeError: module 'comfy.ops' has no attribute 'disable_weight_init'

Cannot import /content/drive/MyDrive/AI/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet module for custom nodes: module 'comfy.ops' has no attribute 'disable_weight_init'

**Comment by freewely** [comment]
I tried 4 different colab notebooks, I also tried the comfyui original colab file.
https://github.com/ltdrdata/ComfyUI-Manager

Unfortunately, it gave the same error in all of them. probably a problem with the colab

**Comment by Kosinkadink** [comment]
The ComfyUI your collab uses is just outdated, by over a month: ComfyUI Revision: 1791 [248d9125] | Released on '2023-12-07'

**Comment by skingfx** [comment]
I found this at the begginning of the run of my noteboook...I think this is the problem and will try and remove the offending files...

Mounting Google Drive...
/
Mounted at /content/drive
/content/drive/MyDrive/AI
/content/drive/MyDrive/AI/ComfyUI
-= Updating ComfyUI =-
Updating 248d912..d76a04b
error: Your local changes to the following files would be overwritten by merge:
	.ci/nightly/update_windows/update_comfyui_and_python_dependencies.bat
	.ci/nightly/windows_base_files/run_nvidia_gpu.bat
Please commit your changes or stash them before you merge.
Aborting

**Comment by Kosinkadink** [comment]
You can also try running "git stash" to get rid of any changes made to those files to avoid the merge conflict.

**Comment by skingfx** [comment]
thank you...will try a get stash.

**Comment by skingfx** [comment]
(get stash didn't work for me...)
( however Kosinkadink was correct my ComfyUI was outdated )

PROBLEM SOLVED by rebuilding my ComfyUI from scratch using this notebook: 
https://colab.research.google.com/github/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb

before rebuilding ComfyUI, I moved my old ComfyUI/models and ComfyUI/output to a tmp location....after running the first cell of the colab notebook...I then moved the above dirs to the new ComyUI dir.

thank you Kosinkadink for your help...even though this ultimately wasn't an AdvancedControlNet issue.

**Comment by freewely** [comment]
> (stash almak benim işime yaramadı...) (ancak Kosinkadink haklıydı, ComfyUI'm güncelliğini kaybetmişti)
> 
> SORUN, şu not defterini kullanarak ComfyUI'mı sıfırdan yeniden oluşturarak ÇÖZÜLDÜ: https://colab.research.google.com/github/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb
> 
> ComfyUI'yi yeniden oluşturmadan önce, eski ComfyUI/modellerimi ve ComfyUI/çıkışımı bir tmp konumuna taşıdım....colab not defterinin ilk hücresini çalıştırdıktan sonra...Daha sonra yukarıdaki dizinleri yeni ComyUI dizinine taşıdım.
> 
> Yardımınız için Kosinkadink'e teşekkür ederim... gerçi sonuçta bu bir AdvancedControlNet sorunu değildi.

Dude, can you share the notebook you edited?

**Comment by skingfx** [comment]
The changes I made to the notebook DID NOT fix this issue.

**Comment by skingfx** [comment]
I rebuilt a new ComfyUI using this notebook:
https://colab.research.google.com/github/ltdrdata/ComfyUI-Manager/blob/main/notebooks/comfyui_colab_with_manager.ipynb

**Comment by freewely** [comment]
thank you dude )

**Comment by MAXadobeX** [comment]
do you solve it?


> ![c2](https://private-user-images.githubusercontent.com/114961562/297159771-f8c63cc2-b60d-41d4-b9a7-057ccb6e4cb2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjgwNDUsIm5iZiI6MTczMzMyNzc0NSwicGF0aCI6Ii8xMTQ5NjE1NjIvMjk3MTU5NzcxLWY4YzYzY2MyLWI2MGQtNDFkNC1iOWE3LTA1N2NjYjZlNGNiMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNTU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05YWNhZWM5NGY2YzBlYTcwMzc5OWFmYzQ4NGQ0ODA4NjNiZmQyZTlmOWFlZWI5Y2NiNjI2ZWI1ZGZmMjcwY2Y1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7TdFlhCovf3VsG2uSmlmYK1HekboE7fAGSm_6G5O-OE) ![c1](https://private-user-images.githubusercontent.com/114961562/297159779-007df660-f963-491a-ba2b-3f0723074da8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjgwNDUsIm5iZiI6MTczMzMyNzc0NSwicGF0aCI6Ii8xMTQ5NjE1NjIvMjk3MTU5Nzc5LTAwN2RmNjYwLWY5NjMtNDkxYS1iYTJiLTNmMDcyMzA3NGRhOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNTU1NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDU2NDBkYjcxMmYwYzhiYzljMTU0Y2VmZDNhYTMzYmNkMzAzNzJkNDI0ZGQ3NTZiM2FhNWQ1MGM5NTlkNTNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P6iCSEuQ9EbguZg5SF0nAcBNExz3cD10shvrVT1m5a4)
> 
> I can't solve this problem for two days. It started suddenly. I am using the following colab notebook.
> 
> https://github.com/dreammachineai/ComfyCloud/blob/main/ComfyCloud_v0_1_2.ipynb
